import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../../style/global.scss';
import { ConfigProvider } from 'antd';

const poppins = Poppins({
  weight: ['400', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: 'var(--font-poppins)',
              colorPrimary: '#f0870f',
              colorText: 'rgba(0,0,0,.85)',
            },
            components: {
              Input: {
                colorBorder: '#ced0d4',
                borderRadius: 4,
                fontSize: 16,
                colorPrimaryText: '#424242',
                colorTextPlaceholder: 'rgb(117, 117, 117)',
              },
              DatePicker: {
                colorBorder: '#ced0d4',
                borderRadius: 4,
                fontSize: 16,
                colorPrimaryText: '#424242',
                colorTextPlaceholder: 'rgb(117, 117, 117)',
              },
              Select: {
                colorBorder: '#ced0d4',
                borderRadius: 4,
                fontSize: 16,
                colorPrimaryText: '#424242',
                colorTextPlaceholder: 'rgb(117, 117, 117)',
              },

              Breadcrumb: {
                linkColor: 'blue',
              },
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
